### ISSUE TITLE
Inconsistency in matching results

### ISSUE THREAD

**Issue by ChristianSchuit** [intuit/fuzzy-matcher#18]
Hi there!

I am running some matching tests with your library on a large dataset of bank transactions. The documents used for matching have a single TEXT field, containing the description of the transaction. On running the matching, I found that some strings that should be an exact match, come back with a probability as low as 0.5. See the below sample:

```
{[{'Immediate Payment Fee,'}]}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 1.0}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
Matching {{[{'Immediate Payment Fee,'}]}, 0.6666666666666666}
```

The top line is the document that is matched and the other lines are the matching results. The implementation of my test is as straightforward as can be, I believe:

```
            // Build document input
            List<Document> documents = new ArrayList<>();
            transactions.stream().forEach(t -> {

                documents.add(new Document.Builder(String.valueOf(index.incrementAndGet()))
                    .addElement(new Element.Builder().setType(ElementType.TEXT).setValue(t.getDescription()).createElement())
                    .createDocument());
            });

            MatchService matchService = new MatchService();
            Map<Document, List<Match<Document>>> matched = matchService.applyMatch(documents);

            for (Iterator<Document> i = matched.keySet().iterator(); i.hasNext(); ) {

                Document d = i.next();
                System.out.println("");
                System.out.println(d.toString());
                matched.get(d).stream().forEach(doc -> {

                    System.out.println("Matching " + doc.toString());
                });
            }
```

I'd love to use your library for my project and hope to contribute, but I think I need to first understand why not all matches are being returned as 1.0 as all the strings are identical.

Thanks!

**Comment by manishobhatia** [comment]
Hi Christian,
I created a branch with your test in it 

https://github.com/intuit/fuzzy-matcher/blob/79f8e0ce3796a7e40632a95239687ca1938497de/src/test/java/com/intuit/fuzzymatcher/component/MatchServiceTest.java#L579

Can you check if this is accurate ? I am unable to see the result you showed.

If you can modify that test with a small set of data you have , I can debug and see where the issue is

**Comment by ChristianSchuit** [comment]
Hi Manish,

Thanks for the quick response.

The only difference I can find is that your test uses List<String> and mine List<Transaction>. I’ll replace my code with List<String> and see if I get the same results. End of the day, I only need the String so that would be a plausible solution.

I’ll try now and let you know.

Thanks!

________________________________
Christian Schuit
Centipod

christian.schuit@centipod.nl<mailto:christian.schuit@centipod.nl>
+31 (0)623 386 645
+27 (0)72 946 8830
www.centipod.nl<http://www.centipod.nl>

**Comment by ChristianSchuit** [comment]
Hi Manish,

﻿When I use the list you have on line 582, I get the correct results. I’ll go dig into my data set and find why it is behaving like this. Manual inspection of the data shows me that they are identical but perhaps I am missing something here.

I’ll close the issue.

Thanks!

________________________________
Christian Schuit
Centipod

christian.schuit@centipod.nl<mailto:christian.schuit@centipod.nl>
+31 (0)623 386 645
+27 (0)72 946 8830
www.centipod.nl<http://www.centipod.nl>

**Comment by ChristianSchuit** [comment]
Just to add for completion:

I tested the following three scenarios:

- Hard-coded string values in the code: works as expected

- Reading data from a file: works as expected

- Reading data from a database: unexpected results

I suspect Spring Data has something to do with this. If I find any more details, I'll drop them here.

Thanks!

**Comment by ChristianSchuit** [comment]
One more update: I have a file with data that, when reading straight from the file, still returns the unexpected results. Is there a way I can share this file with you for testing? This is not information I can share publicly on this thread.

Thanks!

**Comment by manishobhatia** [comment]
if its not too big, can you mail it to manish_bhatia@intuit.com ?

**Comment by ChristianSchuit** [comment]
Hello Manish,

Thanks for this. Please find attached the data file (data2.txt) and the results file containing what I would get when running the below code:


            // Document index

            final AtomicInteger index = new AtomicInteger(0);



            // List for strings

            List<String> list = new ArrayList<>();



            // Read from file

            BufferedReader r = new BufferedReader(new FileReader(new File("./data.txt")));

            String line = null;

            while ((line = r.readLine()) != null) {



                list.add(line);

            }

            r.close();



            // Build document input

            List<Document> documents = new ArrayList<>();

            list.stream().forEach(t -> {



                documents.add(new Document.Builder(String.valueOf(index.incrementAndGet()))

                    .addElement(new Element.Builder().setType(ElementType.TEXT).setValue(t).createElement())

                    .createDocument());

            });



            MatchService matchService = new MatchService();

            Map<Document, List<Match<Document>>> matched = matchService.applyMatch(documents);



            for (Iterator<Document> i = matched.keySet().iterator(); i.hasNext(); ) {



                Document d = i.next();

                System.out.println("");

                System.out.println(d.toString());

                matched.get(d).stream().forEach(doc -> {



                    System.out.println("Matching " + doc.toString());

                });

            }

Many thanks for your support!
________________________________
Christian Schuit
Centipod

christian.schuit@centipod.nl<mailto:christian.schuit@centipod.nl>
+31 (0)623 386 645
+27 (0)72 946 8830
www.centipod.nl<http://www.centipod.nl>

**Comment by manishobhatia** [comment]
Hi Christian,

The code you shared is fine. I think the issue is with visualization of the result in print statement.

If you can replace the last println with this, you should see correct results

`System.out.println("Matching " + doc.getMatchedWith().toString() + " Score : " + doc.getScore().getResult());`

We were printing the "Match" object instead of the Document it matched with. Hope this helps

**Comment by ChristianSchuit** [comment]
Good morning, Manish

Thank you for checking. But if we were printing the Match object, where does the odd score come from?

Thanks!

Sent while on the road. Excuse occasional typos.

**Comment by ChristianSchuit** [comment]
﻿Hi Manish,

Many thanks for your support in this. I have run some more tests and results are great!

Would you be interested in further testing results? We have a very large dataset to play with and I am going to run all of that through the fuzzy matcher.

Christian

________________________________
Christian Schuit
Centipod

christian.schuit@centipod.nl<mailto:christian.schuit@centipod.nl>
+31 (0)623 386 645
+27 (0)72 946 8830
www.centipod.nl<http://www.centipod.nl>

**Comment by ChristianSchuit** [comment]
Great support from this team. Many thanks!
