### ISSUE TITLE
Element constructor does not initialize the scoringFunction with the value passed to the constructor signature

### ISSUE THREAD

**Issue by ssfernando** [intuit/fuzzy-matcher#19]
Line 63 of Element class is assigning the this.scoringFunction to itself when the scoringFunction passed through the constructor is different of null.

https://github.com/intuit/fuzzy-matcher/blob/81d5113a43db24e690a65e0f2437124693a12ff4/src/main/java/com/intuit/fuzzymatcher/domain/Element.java#L63

**Comment by manishobhatia** [comment]
Thanks for reporting this issue. We have a pull https://github.com/intuit/fuzzy-matcher/pull/20
to fix this. Will include it in our next release

**Comment by ssfernando** [comment]
Thank you!

**Comment by manishobhatia** [comment]
Closing issue, fix has been released with 0.4.4 version
