### ISSUE TITLE
Start with non spring project

### ISSUE THREAD

**Issue by thangdc94** [intuit/fuzzy-matcher#3]
My project is a non-spring project. How can I include this dependency without messing up my code.

**Comment by manishobhatia** [comment]
Marked this as enhancement, will remove spring dependency on this project soon.

**Comment by manishobhatia** [comment]
Opened pull request to remove spring
https://github.com/intuit/fuzzy-matcher/pull/4

**Comment by manishobhatia** [comment]
fixed with 0.2.1 version. 

We can now Initialize the MatchService class with a no argument constructor without spring injection.
