### ISSUE TITLE
Support for Age Element type

### ISSUE THREAD

**Issue by manishobhatia** [intuit/fuzzy-matcher#36]
On similar lines to NUMBER element , can we can an AGE element. 
The expectation here is users age can change by a small amount if captured at different times.

So we should see a higher score if the age values are closer (around 1 or 2 years difference) and gets progressively lower with 0 score for age difference over 5 years

**Comment by vaishakhvh** [comment]
Hi @manishobhatia , please let me know if I can work on this issue?

**Comment by manishobhatia** [comment]
Hi @vaishakhvh thanks for taking interest. Yes please go ahead and see if this issue makes sense . Feel free to connect if you have more questions

**Comment by manishobhatia** [comment]
Released this feature with v1.0.4
