### ISSUE TITLE
Find the most similar array

### ISSUE THREAD

**Issue by bacloud14** [intuit/fuzzy-matcher#38]
Hi,

Say I have a list of sentences `Collection<String> sentences` and I want to simply find the most similar among these to another sentence. Is this possible ?

I read the first README file and example there only ingests one input (documents)

Thanks !

**Comment by manishobhatia** [comment]
Hi , 

Yes this is possible. You can consider each sentence as document, which can have just 1 element of type TEXT and feed it as value .

Each documented just needs a unique key as identity. You can use line number for this , other than that there is nothing special
about the Document type

Hope this helps

Thanks

**Comment by manishobhatia** [comment]
closing the issue. Feel free to open a new one, if you things the issue was not resolved , or would like to see some enhancement to the library

**Comment by bacloud14** [comment]
frankly I took a different path thanks for the answer
