### ISSUE TITLE
Address matching: street containing hyphens

### ISSUE THREAD

**Issue by ashakirin** [intuit/fuzzy-matcher#47]
Currently these addresses are not match at all:
Case 1:
- Egger-Lienz-Strasse, 10 AT-4050 Traun
- Egger Lienz Strasse, 10 AT-4050 Traun

Case 2:
- Erdl 5a AT-4861 Schörfling am Attersee
- Erdl 5b AT-4861 Schörfling/Attersee

Are there any option to improve the algorithm in order to consider space and hyphen as equal separators?

Regards,
Andrei.

**Comment by manishobhatia** [comment]
Hi Andrei,

Yes this is possible by overriding the pre-processing function to replace custom separators from data
Here is an example

```
String value = "123_XYZ_Ltd_st, TX";
Function<String, String> customPreProcessing = (str -> str.replaceAll("-", " "));
customPreProcessing = customPreProcessing.andThen(PreProcessFunction.addressPreprocessing());

Element element = new Element.Builder().setType(ADDRESS)
    .setPreProcessingFunction(customPreProcessing)
    .setValue(value)
    .createElement();
```

So as you create the Element object, pass in the `customPreProcessing` function, which will standardize the data before the algorithm considers them for match

Hope this helps

Thanks,
Manish
