### ISSUE TITLE
Matching two strings

### ISSUE THREAD

**Issue by nayan-jyoti** [intuit/fuzzy-matcher#49]
Hi,

I came across this library and tried some very elementary test, matching two strings to find the score.
After going through readme file, several null pointer exceptions and issues already raised, I finally able to play something around that by doing this:
`List<String> input = Arrays.asList(firstStr, secondStr);

		Document document = null;
		List<Document> documentList = new ArrayList<>();
		for (String str : input) {
			document = new Document.Builder(str)
					.addElement(new Element.Builder<String>().setValue(str).setType(ElementType.TEXT).createElement())
					.createDocument();
			documentList.add(document);
		}
		Map<String, List<Match<Document>>> result = matchService.applyMatchByDocId(documentList);

		result.entrySet().forEach(entry -> {
			entry.getValue().forEach(match -> {
				System.out.println("Data: " + match.getData() + " Matched With: " + match.getMatchedWith() + " Score: "
						+ match.getScore().getResult());
			});
		});`
However it is found that:
1. The strings match each other twice, i.e firstStr matches to secondStr and then vice-versa while only a single match was required.
2. I tried string with numbers like "Nayan J Bayan 123" with elementType TEXT, the result came out as a blank map. What should be the element type if I want to check strings containing numbers and special characters? I also tried with ADDRESS type and same blank map was returned.
3. I don't think at all my implementation is correct. What should have been the correct implementation?

Thanks

**Comment by manishobhatia** [comment]
Hi Nayan,

The usage of the library looks accurate .
1. Regarding 2 results being displayed. The intention is to show which documents match with others. If you prefer you could use [applyMatchByGroups](https://github.com/intuit/fuzzy-matcher/blob/666411c258ef1ed816dcca5f4153fd702f5b261e/src/main/java/com/intuit/fuzzymatcher/component/MatchService.java#L124) which will club all the matching elements in a single group and display it. 
2. The numbers as input should not be a problem to match. I think your match result might have fallen below the default threshold (0.5) . Each element is separated by a space and matched with others, in the example  "Nayan J Bayan 123" it will have 4 tokens , so if you have a matching element with more than 2 tokens that are similar it should match.

Here are modifications to your example with applyMatchByGroups

```
       String[] input = new String[]{"Nayan J 123", "Nayan J Bayan 123"};
        
        Document document = null;
        List<Document> documentList = new ArrayList<>();
        for (String str : input) {
            document = new Document.Builder(str)
                    .addElement(new Element.Builder<String>().setValue(str).setType(ElementType.TEXT).createElement())
                    .createDocument();
            documentList.add(document);
        }
        Set<Set<Match<Document>>> result = matchService.applyMatchByGroups(documentList);

        result.forEach(entry -> {
            entry.forEach(match -> {
                System.out.println("Data: " + match.getData() + " Matched With: " + match.getMatchedWith() + " Score: "
                        + match.getScore().getResult());
            });
        });
```

Hope this helps

Thanks

**Comment by nayan-jyoti** [comment]
Hi Manish,

Thanks for prompt response. It was indeed helpful.

`document = new Document.Builder(str).addElement(new Element.Builder<String>().setValue(str)
					.setType(ElementType.TEXT).setThreshold(0.0).createElement()).createDocument();`

I played with few more string pairs after setting threshold value to 0.0 like above.
1. "Vrij Bhooshan" & "VRIJA BHOOSHAN"
2. "Mohammad Ashfaque" & "MOHAMMED ASHFAQUE"
3. "Nayan Bayan" & "Nayan Jyoti"
4. "Nayan Jyoti Bayan Test" &  "Nayan Jyoti B T"

However none of them returned any result. Is it okay?

Thanks

**Comment by nayan-jyoti** [comment]
Thanks for the explanation. Able to get scores after setting threshould at document level.
Thank you again for your time.
