### ISSUE TITLE
Language Supported

### ISSUE THREAD

**Issue by VikasSonu10** [intuit/fuzzy-matcher#51]
Do we have support for Chinese language (character) fuzzy match in this product?

Faster response is appreciated.

**Comment by manishobhatia** [comment]
Hi,
Thanks for taking interest in this library

This library used Apache Soundex internally for matching names, addresses and other nouns which can have spelling or phonetic difference when captured with text.
Unfortunately we do not see Soundex extending it support to languages other than english.

Other than that, the algorithm used here as such is independent of the language. 

If there is enough interest in extending this to other languages, we are open to contribution from the community 

Thanks,
Manish
