### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Cjesus20** [intuit/fuzzy-matcher#59]
Sry if i ask, i want to learn how to do libraries like this and i dont understand how to test your project, really sorry to bother u

**Comment by manishobhatia** [comment]
Hi,

Thanks for taking interest in this project. 

For test and deploying this locally follow the [contributing](https://github.com/intuit/fuzzy-matcher/blob/master/CONTRIBUTING.md) guidelines.

Feel free to see if there are any opportunities you find in the library and open an issue. 

Hope this helps
