### ISSUE TITLE
upgrade commons-text to a non-vulnerable version

### ISSUE THREAD

**Issue by knoll-pointer** [intuit/fuzzy-matcher#66]
A new arbitrary code execution vul has been found in commons-text:
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.9</version>
        </dependency>
https://security.snyk.io/package/maven/org.apache.commons:commons-text/1.9

version 1.10.0 is not vulnerable.

**Comment by sfgvieira** [comment]
This seems to be already fixed on the current codebase but there's no release to maven central, any plans for that?

**Comment by manishobhatia** [comment]
released 1.2.1
